/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.world.dependency;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        final Library classUnderTest = new Library();
        assertFalse("someLibraryMethod should return something", classUnderTest.someLibraryMethod().isEmpty());
    }
}
